# Generated by Django 4.2.19 on 2025-03-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
