# Generated by Django 4.2.19 on 2025-05-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('ISK', 'Industry Skills'), ('PER', 'Personality/Preliminary'), ('FSC', 'Final Screening'), ('GEN', 'General')], default='GEN', max_length=3),
        ),
    ]
