# Generated by Django 4.2.19 on 2025-04-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0003_uploadedfile_pastedtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastedtext',
            name='filepath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
