# Generated by Django 4.2.19 on 2025-04-09 10:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active_interview_app', '0004_pastedtext_filepath'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PastedText',
            new_name='UploadedJobListing',
        ),
        migrations.RenameModel(
            old_name='UploadedFile',
            new_name='UploadedResume',
        ),
    ]
