# Generated by Django 4.2.19 on 2025-04-09 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active_interview_app', '0005_rename_pastedtext_uploadedjoblisting_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedJobListing',
            new_name='UploadedJobListingView',
        ),
        migrations.AddField(
            model_name='chat',
            name='job_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='active_interview_app.uploadedjoblistingview'),
        ),
        migrations.AddField(
            model_name='chat',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='active_interview_app.uploadedresume'),
        ),
    ]
