# Generated by Django 4.2.19 on 2025-04-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0007_uploadedresume_content_uploadedjoblisting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedjoblisting',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
