# Generated by Django 4.2.19 on 2025-04-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0008_uploadedjoblisting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedresume',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
