# Generated by Django 4.2.20 on 2025-04-17 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0010_alter_chat_job_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='difficulty',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
