# Generated by Django 4.2.19 on 2025-04-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0010_alter_chat_job_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='text_audio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
