# Generated by Django 4.2.19 on 2025-04-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0011_chat_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('PER', 'Personality/Preliminary'), ('FSC', 'Final Screening'), ('GEN', 'General'), ('ISK', 'Industry Skills')], default='GEN', max_length=3),
        ),
    ]
