# Generated by Django 4.2.19 on 2025-04-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0012_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('FSC', 'Final Screening'), ('PER', 'Personality/Preliminary'), ('GEN', 'General'), ('ISK', 'Industry Skills')], default='GEN', max_length=3),
        ),
    ]
