# Generated by Django 4.2.19 on 2025-04-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0013_alter_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('ISK', 'Industry Skills'), ('PER', 'Personality/Preliminary'), ('FSC', 'Final Screening'), ('GEN', 'General')], default='GEN', max_length=3),
        ),
    ]
