# Generated by Django 4.2.19 on 2025-04-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0014_alter_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('GEN', 'General'), ('ISK', 'Industry Skills'), ('FSC', 'Final Screening'), ('PER', 'Personality/Preliminary')], default='GEN', max_length=3),
        ),
    ]
