# Generated by Django 4.2.19 on 2025-04-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0011_chat_text_audio'),
        ('active_interview_app', '0015_alter_chat_type'),
    ]

    operations = [
    ]
