# Generated by Django 4.2.20 on 2025-05-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0016_merge_0011_chat_text_audio_0015_alter_chat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='text_audio',
        ),
        migrations.AddField(
            model_name='chat',
            name='key_questions',
            field=models.JSONField(default=dict),
        ),
    ]
