# Generated by Django 4.2.19 on 2025-04-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0016_merge_0011_chat_text_audio_0015_alter_chat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='text_audio',
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('PER', 'Personality/Preliminary'), ('GEN', 'General'), ('FSC', 'Final Screening'), ('ISK', 'Industry Skills')], default='GEN', max_length=3),
        ),
    ]
