# Generated by Django 4.2.20 on 2025-04-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0018_alter_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('GEN', 'General'), ('FSC', 'Final Screening'), ('ISK', 'Industry Skills'), ('PER', 'Personality/Preliminary')], default='GEN', max_length=3),
        ),
    ]
