# Generated by Django 4.2.20 on 2025-05-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0019_alter_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('ISK', 'Industry Skills'), ('PER', 'Personality/Preliminary'), ('GEN', 'General'), ('FSC', 'Final Screening')], default='GEN', max_length=3),
        ),
    ]
