# Generated by Django 4.2.20 on 2025-05-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0021_alter_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('FSC', 'Final Screening'), ('ISK', 'Industry Skills'), ('GEN', 'General'), ('PER', 'Personality/Preliminary')], default='GEN', max_length=3),
        ),
    ]
