# Generated by Django 4.2.19 on 2025-05-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0022_alter_chat_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professionalism', models.IntegerField()),
                ('subject_knowledge', models.IntegerField()),
                ('clarity', models.IntegerField()),
                ('overall', models.IntegerField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='active_interview_app.chat')),
            ],
        ),
    ]
