# Generated by Django 4.2.20 on 2025-05-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0023_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('PER', 'Personality/Preliminary'), ('GEN', 'General'), ('FSC', 'Final Screening'), ('ISK', 'Industry Skills')], default='GEN', max_length=3),
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
