# Generated by Django 4.2.19 on 2025-05-06 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active_interview_app', '0017_remove_chat_text_audio_chat_key_questions'),
        ('active_interview_app', '0023_chart'),
    ]

    operations = [
    ]
